### ISSUE TITLE
Can I use this model to perform transfer learning for supervised MT with BERT?

### ISSUE THREAD

**Issue by MichaelZhouwang** [deep-spin/OpenNMT-APE#1]
Thanks for your great work!  After reading the paper and your code, I find that if I do not add mt results with [sep] in the srcmt file, then the model is actually performing transfer learning for supervised MT with BERT? Is this right and have you tried this? Thanks!

**Comment by goncalomcorreia** [comment]
Yes, that's right! It can also work as BERT for MT :)
