### ISSUE TITLE
Serve pretrained model as API

### ISSUE THREAD

**Issue by masus04** [deep-spin/OpenNMT-APE#11]
I am trying to start a server using a pretrained model. Am I correct in assuming the server.py is used to start an inference server?

As far as I understand the available models are configured in the /available_models/conf.json file. Is there any documentation on the options available for this config file?

**Comment by goncalomcorreia** [comment]
Hi, this is an old fork of [OpenNMT-py](https://github.com/OpenNMT/OpenNMT-py). This seems like an issue specific to that repository. I never used the server.py script so I don't know if the changes in this fork have an effect on it in any way

**Comment by masus04** [comment]
Ok, thank you.
Is there any other existing method to serve a pretrained model?

**Comment by goncalomcorreia** [comment]
Not that I know of.

**Comment by goncalomcorreia** [comment]
You can try to see the documentation for server.py in the original OpenNMT-py repository. If you find the issue, I'll gladly accept a PR :)

**Comment by masus04** [comment]
Alright, will check, thank you :+1:
