### ISSUE TITLE
Where can I find the code of this paper?

### ISSUE THREAD

**Issue by lvbaiyang** [deep-spin/OpenNMT-APE#8]
Where can I find the code of this paper: "Unbabel’s Submission to the WMT2019 APE Shared Task: BERT-Based Encoder-Decoder for Automatic Post-Editing"?
For example, where is the "Conservativeness penalty"?

**Comment by zhaofuchen** [comment]
兄弟，你说的是啥意思，没看懂。

**Comment by lvbaiyang** [comment]
这篇文章的作者在WMT2019发了一篇改进版的论文，里面新增了如Conservativeness penalty的机制，但是我没找到源码，老哥你有么

**Comment by zhaofuchen** [comment]
抱歉没有哦

**Comment by goncalomcorreia** [comment]
There is no released code for that paper
